### PR TITLE
fix(instrumentation-fs): fix `fs.exists` when it's util.promisified

### LINKED ISSUE #1185: fs.exists with util.promisify causes to unhandled rejection
### What version of OpenTelemetry are you using?
```  
"name": "@opentelemetry/api",
"version": "1.2.0"
```

**Latest installed globally.**

Installed dependencies:
 npm i --unsafe-perm -g @splunk/otel @opentelemetry/api @opentelemetry/instrumentation-http @opentelemetry/instrumentation-express @opentelemetry/instrumentation-pino @opentelemetry/instrumentation-winston @opentelemetry/instrumentation-nestjs-core @opentelemetry/instrumentation-ioredis @opentelemetry/instrumentation-fs opentelemetry-instrumentation-mongoose @opentelemetry/instrumentation-dns @opentelemetry/instrumentation-amqplib 

Note: Also tried to install everything except fs but same behaviour.

### What version of Node are you using?
v16.17.0

### What did you do?
Reproducing is easy:

test.mjs
```mjs
import * as fs from 'fs';
import * as util from 'util'; 

const result = await util.promisify(fs.exists)('./index.js');
console.log(result);
```

### What did you expect to see?
fs.exists should return 'true' as a resolved value and not as a rejected value.

### What did you see instead?

Executing node with `node -r @splunk/otel/instrument test.mjs` causes to this error:

node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^
true
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Without -r @splunk/otel/instrument it works as expected.

### Additional context
It looks like the promisified fs.exists is handled incorrectly (CB parameters) by opentelemetry and Promise.reject is called with (true) instead of resolve.

### PR DESCRIPTION
**Pull request by Rauno56**
## Which problem is this PR solving?

`fs.exists` has an unusual signature with the callback never returning an error.
To get around that when using `util.promisify`, custom promisifing function is defined.
Our instrumentation doesn't take that into account.

Fixes #1185

## Short description of the changes

Added separate patcher for `fs.exists` that is aware of the above and define a new custom promisifying function for our patched function.

### CODE REVIEW

**Review by vmarchaud — APPROVED** [review]

File: plugins/node/instrumentation-fs/src/instrumentation.ts [hunk 1]
```diff
@@ -63,6 +64,19 @@ export default class FsInstrumentation extends InstrumentationBase<FS> {
             );
           }
           for (const fName of CALLBACK_FUNCTIONS) {
+            if (fName === 'exists') {
+              // handling separately because of the inconsistent cb style:
+              // `exists` doesn't have error as the first argument, but the result
+              if (isWrapped(fs[fName])) {
```
Comment (Flarna) [inline plugins/node/instrumentation-fs/src/instrumentation.ts:70]: there is no need to duplicate this if. could be moved up before `if (fName === 'exists') {` once for all.

**Review by Flarna — APPROVED** [review]

File: plugins/node/instrumentation-fs/src/instrumentation.ts (hunk 1 above)
Comment (Rauno56) [reply plugins/node/instrumentation-fs/src/instrumentation.ts:70]: Absolutely! Thanks!
