### PR TITLE
fix: remove types of the instrumented libs form public apis

### LINKED ISSUE #1217: Mongoose instrumentation imports types from the underlying package
`utils.d.ts` and `mongoose.d.ts` of the build assets import types from `mongoose`:

```
import type [...] from 'mongoose';
```

Which means that the compilation fails, if the user has not installed the `mongoose` package - happens with metapackage users for example.

This needs to be fixed by removing all references of the mongoose types from the public APIs.

### LINKED ISSUE #1218: Dataloader instrumentation imports types from the underlying package
`instrumentation.d.ts` of the build assets import types from `dataloader`:

```
import type [...] from 'dataloader';
```

Which means that the compilation fails, if the user has not installed the `dataloader` package - happens with metapackage users for example.

This needs to be fixed by removing all references to any of the dataloader types from the public APIs.

### PR DESCRIPTION
**Pull request by Rauno56**
## Which problem is this PR solving?

Fixes #1217
Fixes #1218

## Short description of the changes

- Cast Dataloaders module definitions to `InstrumentationNodeModuleDefinition<unknown>`
- Turned `patch` and `unpatch` methods on mongoose instrumentation private
- Cast the Collection argument in mongoose untils inside the function as opposed to having the type on the signature

### CODE REVIEW

**Comment by Rauno56** [comment]
Requesting reviews from the component owners: @henrinormak and @blumamir :pray:

**Review by henrinormak — APPROVED** [review]
The dataloader part looks good, the mongoose changes syntactically make sense, but I can't speak for their logical need.

**Review by MSNev — APPROVED** [review]

**Review by vmarchaud — APPROVED** [review]

File: plugins/node/instrumentation-mongoose/src/utils.ts [hunk 1]
```diff
@@ -20,8 +20,10 @@ import { safeExecuteInTheMiddle } from '@opentelemetry/instrumentation';
 import { SemanticAttributes } from '@opentelemetry/semantic-conventions';
 
 export function getAttributesFromCollection(
-  collection: Collection
+  _collection: unknown
```
Comment (blumamir) [inline plugins/node/instrumentation-mongoose/src/utils.ts:23]: I might be missing something, but why is this function part of the public api? it is not exported in `index.ts`

**Review by blumamir — APPROVED** [review]

File: plugins/node/instrumentation-mongoose/src/utils.ts (hunk 1 above)
Comment (Rauno56) [reply plugins/node/instrumentation-mongoose/src/utils.ts:23]: It is not exported to `index.ts`, but it's exported from utils. I expected TS to recursively import ts files and compile them. It seems that I was wrong and in the normal case utils is not compiled. Only when 

```
import * as mongooseUtils from '@opentelemetry/instrumentation-mongoose/build/src/utils';
```

is run explicitly, the problem occurs. Is there a compiler option that turns that process recursive?

That said, if I understand the situation correctly, we don't have to remove the type from that signature. Thanks for pointing that out, @blumamir!

**Review by dyladan — APPROVED** [review]

File: plugins/node/instrumentation-mongoose/src/utils.ts (hunk 1 above)
Comment (blumamir) [reply plugins/node/instrumentation-mongoose/src/utils.ts]: > Is there a compiler option that turns that process recursive?

From what I know, typescript is compiling only the single `.d.ts` file that is declared in `package.json` like this:
```js
{
  "types": "index.d.ts"
}
```

This file in turn can `import` other type files (or not), but since `utils.d.ts` is not imported from `index.d.ts`, then typescript never encounters `import * from 'mongoose'` so there are no issues.
This is only my understanding, but I could be missing some important details. typescript is so complicated 😅
