### PR TITLE
fix(pg-values): values should be parsable when enhancedDatabaseRepoting:true

### LINKED ISSUE #1235: pg instrumentation: enhancedDatabaseReporting value is not parsable
### What version of OpenTelemetry are you using?
 "@opentelemetry/instrumentation-pg": "0.31.1"

### What version of Node are you using?
16

### What did you do?
Executed the following pg query with instrumentation config `enhancedDatabaseReporting: true`
```js
    const res = await client.query('SELECT $1::text as message1, $2::text as message2', ['Hello,World', 'foo,bar']);
```

### What did you expect to see?
I expected to be able to tell what the query values are for this operation.

### What did you see instead?
I got this value in the `db.postgresql.values` attribute: `"[Hello,World,foo,bar]"`
This text is not reversible. all of these arrays will yield the same attribute value and there is no way to differentiate them in a deterministic way:
```js
['Hello,World', 'foo,bar']
['Hello', 'World,foo,bar']
['Hello,World,foo', 'bar']
```

### Additional context
The reason is that [this data is serialized](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/682d6107b7285829bb72e592936c585ccdfab16a/plugins/node/opentelemetry-instrumentation-pg/src/utils.ts#L48) in a non-standard, non-reversible way:
```js
function arrayStringifyHelper(arr: Array<unknown>): string {
  return '[' + arr.toString() + ']';
}
```

I suggest using `JSON.stringify`

### PR DESCRIPTION
**Pull request by haddasbronfman**
## Which problem is this PR solving?

Fixes #1235 

## Short description of the changes

use `JSON.stringify()` instead of `arrayStringifyHelper`

### CODE REVIEW

File: plugins/node/opentelemetry-instrumentation-pg/src/utils.ts [hunk 1]
```diff
@@ -158,7 +155,7 @@ export function handleConfigQuery(
   ) {
     span.setAttribute(
       AttributeNames.PG_VALUES,
-      arrayStringifyHelper(queryConfig.values)
+      JSON.stringify(queryConfig.values)
```
Comment (blumamir) [inline plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:158]: I recommend wrapping this function with try-catch, as `JSON.stringify` can throw for cyclic objects, and `queryConfig.values` is a user supplied argument for which we cannot assume anything.

**Review by blumamir — COMMENTED** [review]
Too bad https://github.com/open-telemetry/opentelemetry-specification/pull/3092
Didn't get through. 

Thanks for fixing this. Left just one small note about `JSON.stringify` can throw exception

File: plugins/node/opentelemetry-instrumentation-pg/src/utils.ts [hunk 2]
```diff
@@ -156,10 +152,14 @@ export function handleConfigQuery(
...
     Array.isArray(queryConfig.values)
   ) {
-    span.setAttribute(
-      AttributeNames.PG_VALUES,
-      arrayStringifyHelper(queryConfig.values)
-    );
+    try {
+      span.setAttribute(
+        AttributeNames.PG_VALUES,
+        JSON.stringify(queryConfig.values)
```
Comment (Flarna) [inline plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:158]: values may hold objects or buffers and [PG has some handling](https://node-postgres.com/features/queries#parameterized-query) how this is converted.
Not sure if `JSON.stringify` fits well in that cases.

e.g. `JSON.stringify([Buffer.from("abc")])` results in `'[{"type":"Buffer","data":[97,98,99]}]'`

It differs also from the proposal done in spec repo

Comment (haddasbronfman) [reply plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:158]: thanks for this comment.
Do you have any idea what can be used instead of 'stringify'?

Comment (Flarna) [reply plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:158]: I think your initial idea to use an array of strings should be fine. Likely some conversion code is needed to handle `null`/`undefined`, buffers, and objects similar as pg does.

File: plugins/node/opentelemetry-instrumentation-pg/src/utils.ts [hunk 3]
```diff
@@ -153,10 +153,19 @@ export function handleConfigQuery(
     Array.isArray(queryConfig.values)
   ) {
     try {
-      span.setAttribute(
-        AttributeNames.PG_VALUES,
-        JSON.stringify(queryConfig.values)
-      );
+      const convertedValues = queryConfig.values.map(value => {
+        if (!value) {
```
Comment (Flarna) [inline plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:157]:
```suggestion
        if (value == null) {
```
only null/undefined should fit here, not 0 or empty strings

File: plugins/node/opentelemetry-instrumentation-pg/src/utils.ts [hunk 4]
```diff
@@ -153,10 +153,19 @@ export function handleConfigQuery(
...
+          return 'null';
+        } else if (value instanceof Buffer) {
+          return value.toString();
```
Comment (Flarna) [inline plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:160]: maybe use "hex" formatting to get a consistent format.
e.g.
`Buffer.from([65, 0, 1, 2]).toString()` => `'A\x00\x01\x02'`
`Buffer.from([65, 0, 1, 2]).toString("hex")` => `'41000102'`

File: plugins/node/opentelemetry-instrumentation-pg/src/utils.ts [hunk 5]
```diff
@@ -153,10 +153,19 @@ export function handleConfigQuery(
...
   ) {
     try {
-      span.setAttribute(
-        AttributeNames.PG_VALUES,
-        JSON.stringify(queryConfig.values)
-      );
+      const convertedValues = queryConfig.values.map(value => {
+        if (!value) {
+          return 'null';
+        } else if (value instanceof Buffer) {
```
Comment (Flarna) [inline plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:159]:
```suggestion
        } else if (Buffer.isBuffer(value)) {
```

File: plugins/node/opentelemetry-instrumentation-pg/src/utils.ts [hunk 6]
```diff
@@ -153,10 +153,19 @@ export function handleConfigQuery(
...
+          return value.toString();
+        } else if (typeof value === 'object') {
+          return JSON.stringify(value);
```
Comment (Flarna) [inline plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:162]: Should we try to use a potential existing `toPostgres` function like PG does?

In general a try/catch around this conversions is likely a good idea as `JSON.stringify` could throw.

File: plugins/node/opentelemetry-instrumentation-pg/src/utils.ts (hunk 3 above)
Comment (haddasbronfman) [reply plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:157]: good catch. thanks!

File: plugins/node/opentelemetry-instrumentation-pg/src/utils.ts (hunk 5 above)
Comment (haddasbronfman) [reply plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:159]: Why prefer `isBuffer()` over `instanceof`? it seems in the code that it's the same: 
https://github.com/nodejs/node/blob/main/lib/buffer.js#L556

Comment (Flarna) [reply plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:159]: ah ok. Feel free to keep it as is. I was assuming that the existence of `Buffer.isBuffer()` indicates that there is some more magic included there.

File: plugins/node/opentelemetry-instrumentation-pg/src/utils.ts (hunk 6 above)
Comment (haddasbronfman) [reply plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:162]: Ok. added 'toPostgres' condition.

We already have a try/catch for all this conversion, but I added a printout of the error itself now.

**Review by Flarna — APPROVED** [review]
Maybe tune tests a bit to add e.g. a `toPostgres()`, empty string, 0, NaN cases if you find some time.

File: plugins/node/opentelemetry-instrumentation-pg/src/utils.ts (hunk 4 above)
Comment (haddasbronfman) [reply plugins/node/opentelemetry-instrumentation-pg/src/utils.ts]: if we use "hex", then the value of `Buffer.from('abc').toString('hex')` is `616263` rather than `abc`. is that what we want to present to the user?

Comment (Flarna) [reply plugins/node/opentelemetry-instrumentation-pg/src/utils.ts]: not sure what is best here. If buffers actually contain strings using hex encoding is not nice. But if buffers hold binary data it's quite nice. I have no strong opinion here.

By the way, should be also consider some len limit here or just rely on SDK built in limits?

Comment (haddasbronfman) [reply plugins/node/opentelemetry-instrumentation-pg/src/utils.ts:160]: 1. I left toString() as is. without 'hex'.
2. I added a test for 'toPostgres'.

**Comment by haddasbronfman** [comment]
@Flarna I added a test. do you want to take a look or is it ok to merge?

**Review by Flarna — APPROVED** [review]

**Comment by Flarna** [comment]
fine for me.
as of now @rauno56 is the owner of this instrumentation but not sure if component_owners.yml is up to date.
