### PR TITLE
fix(instrumentation-user-interaction): support clicks in React apps

### LINKED ISSUE #168: onclick - react, zone.js
Investigate problem with onclick event for react when using plugin for user interaction , react plugin, xmlhttprequest plugin, and zone manager.
More context here -> https://github.com/open-telemetry/opentelemetry-js-contrib/pull/164#issuecomment-668811140

### PR DESCRIPTION
**Pull request by kkruk-sumo**
## Which problem is this PR solving?

This fixes #168.

React <17 listens on `document`. It didn't work previously, because we were only listening on `HTMLElement` instances.
React >=17 listens on a page root (usually a div or `document.body`), so all spans had the same xpath.

## Short description of the changes

**This PR changes current behaviour**.

The good news is that the current behaviour is undocumented - I didn't have to change existing unit tests.

Previously the element on which the listener has been added was taken into a span (in `div.addEventListener` - the `div` was always in span's xpath, not the clicked child).
After this change, the `event.target` will be taken (the actually clicked element).

### CODE REVIEW

File: plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts [hunk 1]
```diff
@@ -265,16 +265,19 @@ export class UserInteractionInstrumentation extends InstrumentationBase<unknown>
...
+          const target = event?.target;
           if (event) {
             parentSpan = plugin._eventsSpanMap.get(event);
           }
           if (once) {
             plugin.removePatchedListener(this, type, listener);
           }
-          const span = plugin._createSpan(target, type, parentSpan);
+          const span =
+            target instanceof HTMLElement
```
Comment (johnbley) [inline plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts:278]: `_createSpan` already has a number of "does this have enough information to produce a good span? -> if not, `undefined`" checks, and I think this one belongs inside `_createSpan` rather than outside it, to keep said logic centralized.

File: plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts [hunk 2]
```diff
@@ -439,10 +442,14 @@ export class UserInteractionInstrumentation extends InstrumentationBase<unknown>
...
-        const target: HTMLElement | undefined = task.target;
+        const event =
+          Array.isArray(applyArgs) && applyArgs[0] instanceof Event
+            ? applyArgs[0]
+            : undefined;
+        const target = event?.target;
         let span: api.Span | undefined;
         const activeZone = this;
-        if (target) {
+        if (target instanceof HTMLElement) {
```
Comment (johnbley) [inline plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts:452]: See previous comment - if `_createSpan` does this check, it doesn't need to be repeated elsewhere.

File: plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.nozone.test.ts [hunk 3]
```diff
@@ -410,6 +415,122 @@ describe('UserInteractionInstrumentation', () => {
...
+            }).then(() => {});
+            break;
+        }
+      };
+
+      document.addEventListener('click', listener);
+
+      try {
+        btn1.click();
+        btn2.click();
```
Comment (johnbley) [inline plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.nozone.test.ts:445]: I appreciate this test (having two targets and ensuring that the span names properly line up)!

File: plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.test.ts [hunk 4]
```diff
@@ -40,6 +40,12 @@ const FILE_URL =
   'https://raw.githubusercontent.com/open-telemetry/opentelemetry-js/main/package.json';
 
 describe('UserInteractionInstrumentation', () => {
+  afterEach(() => {
+    while (document.body.lastChild) {
+      document.body.removeChild(document.body.lastChild);
```
Comment (johnbley) [inline plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.test.ts:45]: I'm not sure why this is necessary?  Perhaps a comment?

**Review by johnbley — CHANGES_REQUESTED** [review]

File: plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.test.ts (hunk 4 above)
Comment (kkruk-sumo) [reply plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.test.ts:46]: Comment added.

**Review by johnbley — APPROVED** [review]
Looks good now, thanks for the edits!

**Review by MSNev — APPROVED** [review]

**Review by obecny — APPROVED** [review]
